hmpps-auth:
  url: "http://localhost:8090/auth"

general-ledger-api:
  url: http://localhost:8084
  client:
    id: hmpps-prisoner-finance-general-ledger-api
    secret: clientsecret

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

hmpps:
  sqs:
    provider: localstack
    queues:
      domainevents:
        queueName: prisoner-finance-event-queue
        dlqName: prisoner-finance-event-dlq
        subscribeTopicId: domainevents
        subscribeFilter: '{"eventType":[ "core-person-record.prison.record.created" ] }'
    topics:
      domainevents:
        arn: arn:aws:sns:eu-west-2:000000000000:11111111-2222-3333-4444-555555555555